  frame: /map
  map_resolution: 0.05
  map_origin_x: -35.025
  map_origin_y: -12.025
  map_size_x: 1200
  map_size_y: 700
  occupancy_prob_threshold: 0.8
  lidar_update_increment: 0.1
  lidar_update_decrement: 0.05
  
  
  horizontal_lidar_pose_tf_name: /base_laser_link
  horizontal_lidar_topic_name: /base_scan
  camera_pose_tf_name: /base_laser_link
  camera_scan_topic_name: /camera_scan_node/camera_scan
  
  map_publish_rate: 4.0