publish_transforms: true
transform_publish_rate: 10.0

#scan matching
scan_match_ang_res: 0.05
scan_match_met_res: 0.1
scan_match_dx: 5
scan_match_dy: 5
scan_match_dz: 0
scan_match_dyaw: 8

#other
map_publish_rate: 1.0

# debug
publish_inner_maps: true
