#frame: map
##map params
#map_resolution: 0.1
#map_origin_x: -1.025
#map_origin_y: -12.025
#map_origin_z: 0.0
#map_size_x: 1200
#map_size_y: 700
#map_size_z: 50

#scan matching
scan_match_ang_res: 0.05
scan_match_met_res: 0.1
scan_match_dx: 5
scan_match_dy: 5
scan_match_dz: 0
scan_match_dyaw: 8

#other
map_publish_rate: 1.0

# debug
publish_inner_maps: true
