frame: /map
#map params
map_resolution: 0.05
map_origin_x: -35.025
map_origin_y: -12.025
map_origin_z: 0.0
map_size_x: 1200
map_size_y: 700
map_size_z: 120
 
#map names
robot_0_map_name: /Map1/exploration_map_node/exploration_map_update
robot_1_map_name: /Map2/exploration_map_node/exploration_map_update

#robot pose names
robot_0_pose_name: /Map1/exploration_map_node/robot_pose
robot_1_pose_name: /Map2/exploration_map_node/robot_pose

#goal list name
goal_list_name: /robot_goals
 
#scan matching
scan_match_ang_res: 0.05
scan_match_met_res: 0.1
scan_match_dx: 20
scan_match_dy: 20
scan_match_dz: 0
scan_match_dyaw: 20

#other 
map_publish_rate: 1.0
 