 frame: /map
 map_resolution: 0.05
 map_origin_x: -35.025
 map_origin_y: -12.025
 map_size_x: 1200
 map_size_y: 700
 
 robot_0_map_name: /Segbot/exploration_map_node/exploration_map
 robot_1_map_name: /Hexarotor/exploration_map/exploration_map
 
 map_publish_rate: 1.0
 
 