#frame: map
#map_resolution: 0.1
#map_origin_x: -1.025
#map_origin_y: -12.025
#map_origin_z: 0.0
#map_size_x: 1200
#map_size_y: 700
#map_size_z: 50

ground_plane_height_threshold: -3.0
unnocupied_prob_threshold: 0.4
occupancy_prob_threshold: 0.6
lidar_update_increment: 0.2
lidar_update_decrement: 0.05
min_sensor_distance_threshold: 0.6

horizontal_lidar_pose_tf_name: fixed_laser_frame
vertical_lidar_pose_tf_name: panning_laser_frame
camera_pose_tf_name: fixed_laser_frame
robot_pose_tf_name: body_frame
robot_radius: 1.0
robot_height: 0.5

map_publish_rate: 1.0
number_of_scans_to_skip: 5
publish_debug_messages: false
